### ISSUE TITLE
Contents are not renames inside the .config files.

### ISSUE THREAD

**Issue by finddata** [hakonhagland/finddata#1]
**elsif ( -f $name ) {
            if (( my $base_name = $name) =~ s/\.config$// ) {
                if ( $name_map->{$base_name} ) {
                    p $base_name;
                    my $new_name = $name_map->{$base_name} . '.config';
                    rename_file_or_dir( $name, $new_name );
                    change_file( $new_name, $name_map, $regex );
                }
            }
        }**
The above part is missing something.

**Comment by hakonhagland** [comment]
Ok, I sent you a new email that should fix this issue. Please check

**Comment by finddata** [comment]
OKay.

**Comment by finddata** [comment]
sub change_file {
print "enter";
    my ( $fn, $map, $regex ) = @_;
    open ( my $fh, '<', $fn ) or die "Could not open file '$fn': $!";
    my $str = do { local $/; <$fh> };
    close $fh;
    my $num_replacements = $str =~ s/($regex)/$map->{$1}/ge;
    if ( $num_replacements ) {
        write_new_file( $fn, \$str );
    }
}

sub write_new_file {
print "enter1";
    my ( $fn, $str ) = @_;
    open ( my $fh, '>', $fn ) or die "Could not open file '$fn': $!";
    print $fh $$str;
    close $fh;
}

Why the print statement inside the sub routine prints nothing.If it is accessing those sub routines it should print the statements.Here it prints nothing

**Comment by hakonhagland** [comment]
It prints fine :), you just need to put a newline behind the print:

print "enter\n";



2017-03-16 12:48 GMT+01:00 finddata <notifications@github.com>:

**Comment by finddata** [comment]
I checked it.It is not printing any thing .

**Comment by finddata** [comment]
sub change_file {
print "enter\n";
    my ( $fn, $map, $regex ) = @_;
    open ( my $fh, '<', $fn ) or die "Could not open file '$fn': $!";
    my $str = do { local $/; <$fh> };
    close $fh;
    my $num_replacements = $str =~ s/($regex)/$map->{$1}/ge;
    if ( $num_replacements ) {
        write_new_file( $fn, \$str );
    }
}

sub write_new_file {
print "enter1\n";
    my ( $fn, $str ) = @_;
    open ( my $fh, '>', $fn ) or die "Could not open file '$fn': $!";
    print $fh $$str;
    close $fh;
}

**Comment by hakonhagland** [comment]
Ok, that is weird.. Here is what I get:

$ run.sh
enter
enter1
enter


2017-03-16 12:55 GMT+01:00 finddata <notifications@github.com>:

**Comment by finddata** [comment]
Does .sh files are necessary for me.to keep at my location.I think you had created it for making directories.Am i right?

**Comment by hakonhagland** [comment]
If you do not use "run.sh", you need to delete the "newdir" structure
before running the script:

 rm -rf newdir/



2017-03-16 13:04 GMT+01:00 finddata <notifications@github.com>:

**Comment by finddata** [comment]
Yes . I had tried that too

**Comment by finddata** [comment]
Is there any other way to do the same process with different subroutines.Instead of using if and else if in the same sub routine.

**Comment by finddata** [comment]
Even i too feel weird why  it is not working.Am struggling to fix this issue.Thats why checking wiht you any other alternate ways to do it.

**Comment by finddata** [comment]
Hi,

Is there any things to change with my script.

**Comment by hakonhagland** [comment]
Hello! Are there still problems? It works fine here :)

2017-03-17 7:25 GMT+01:00 finddata <notifications@github.com>:

**Comment by finddata** [comment]
Is it.For me it shows problem.Could you please share your screenshots

**Comment by hakonhagland** [comment]
$ run.sh
enter
enter1
enter

$ show.sh
c1 : 0% : 0% c11 c1 c1
newdir
└── DEMO
    ├── DEMO.config
    └── top
        └── DV
            ├── DV.config
            ├── rev1
            │   └── rev1.config
            └── rev2
                └── rev2.config

5 directories, 4 files
DV : 0% : 0% c11 DV DV


2017-03-17 9:46 GMT+01:00 finddata <notifications@github.com>:

**Comment by finddata** [comment]
I had used the same code then why it not works for me.#!/usr/local/bin/perl
use strict;
use warnings;

use Data::Dumper;
use File::Path       qw( make_path );
use File::Copy  qw( copy move);
use File::Find::Rule qw( );
use Cwd qw(getcwd);
use File::Basename;
use File::Copy ();
use File::Remove ();
use File::Basename;
use File::Find;
use File::Spec;
use Getopt::Long   qw( GetOptions );
use Cwd;

##TO CHECK THE USAGE AT COMMAND LINE ARGUMENTS##
sub usage {
   if (@_) {
      my ($msg) = @_;
      chomp($msg);
      print(STDERR "$msg\n");
   }

   my $prog = basename($0);
   print(STDERR "$prog --help for usage\n");
   exit(1);
}

sub help {
   my $prog = basename($0);
   print(STDERR "$prog [options] -output output_dir\n");
   print(STDERR "$prog --help\n");
   exit(0);
}

##GETTING INPUT/OUTPUT FILE FROM COMMAND LINE ARGUMENTS##

GetOptions(
    'help|h|?' => \&help,
    'prjroot=s' => \my $input_dir,
    'outdir=s' => \my $output_dir,
    'mapfile=s' => \my $mapfile,
)
    or usage();

##CREATING THE DIRECTORIES FROM COMMAND LINE ARGUMENTS##
mkdir $output_dir ;

##COPYING THE CONFIG FILES FROM SOURCE TO DESTINATION### 
my %created;
for my $in (
   File::Find::Rule
   ->maxdepth(5)
   ->file()
   ->prune()
   ->name(qr/^[^.].*\.config$/)
   ->in($input_dir)
) {
    my $match_file = substr($in, length($input_dir) + 1); 
    my ($match_dir) = $match_file =~ m{^(.*)/} ? $1 : '.';
    my $out_dir = $output_dir . '/' . $match_dir;
    my $out     = $output_dir . '/' . $match_file;
    make_path($out_dir) if !$created{$out_dir}++;
    copy($in, $out);
}

##TO RENAME DIRECTORIES AND RENAME THE CONTENTS OF THE .CONFIG FILES AS PER MATCHING WITH MAPFILE.TXT CONTENTS##
my $name_map = read_map( $mapfile );
my ($regex) = map {qr /\b(?:$_)\b/ } join '|', map {quotemeta} keys %$name_map;

my $top_dir = $output_dir;

rename_dirs( $top_dir, $name_map, $regex );
sub rename_dirs {
    my ( $top_dir, $name_map, $regex ) = @_;
    opendir (my $dh, $top_dir) or die "Can't open $top_dir: $!";
    my $save_dir = getcwd();
    chdir $top_dir;
    while (my $name = readdir $dh) {
        next if ($name eq '.') or ($name eq '..'); 
        if ( ( -d $name ) && ( exists $name_map->{$name} ) ) {
            my $new_name = $name_map->{$name};
            rename_file_or_dir( $name, $new_name );
            $name = $new_name;            
        }       
        elsif ( -f $name ) {
            if (( my $base_name = $name) =~ s/\.config$// ) {
                if ( $name_map->{$base_name} ) {
                    my $new_name = $name_map->{$base_name} . '.config';
                    rename_file_or_dir( $name, $new_name );
                    change_file( $new_name, $name_map, $regex );
                }
            }
        }
        else
        {
         #print "  --> is not a directory", "\n";
         }

        if ( -d $name) { 
            
            rename_dirs( $name, $name_map, $regex );
            
            } 
    }
    chdir $save_dir;
}


sub change_file {
    my ( $fn, $map, $regex ) = @_;
    open ( my $fh, '<', $fn ) or die "Could not open file '$fn': $!";
    my $str = do { local $/; <$fh> };
    close $fh;
    my $num_replacements = $str =~ s/($regex)/$map->{$1}/ge;
    if ( $num_replacements ) {
        write_new_file( $fn, \$str );
    }
}

sub write_new_file {
    my ( $fn, $str ) = @_;
    open ( my $fh, '>', $fn ) or die "Could not open file '$fn': $!";
    print $fh $$str;
    close $fh;
}

sub rename_file_or_dir {

    my ( $name, $new_name ) = @_;
    File::Copy::move( $name, $new_name )
        or die "Could not rename '$name' as '$new_name': $!";
        #print $name;
}

sub read_map {
    my ( $fn ) = @_;

    my %name_map;

    open( my $fh, '<', $fn ) or die "Could not open file '$fn': $!";
    while( my $line = <$fh> ) {
        chomp $line;
        my @fields = split /:/, $line;
       # print @fields;
        if ( @fields == 3 ) {
            $name_map{$fields[2]} = $fields[1];
        }
    }
    close $fh;
    return \%name_map;
}

**Comment by hakonhagland** [comment]
Ok, let's look at this..what output do you get when you run "show.sh"?

2017-03-17 10:18 GMT+01:00 finddata <notifications@github.com>:

**Comment by hakonhagland** [comment]
Here I can see one with your code:

->name(qr/^[^.]..config$/)

it should be:

->name(qr/^[^.].*\.config$/)



2017-03-17 10:21 GMT+01:00 Håkon Hægland <hakon.hagland@gmail.com>:

**Comment by hakonhagland** [comment]
Here is another problem:

write_new_file( $fn, $str );

it should be:

write_new_file( $fn, \$str );



2017-03-17 10:25 GMT+01:00 Håkon Hægland <hakon.hagland@gmail.com>:

**Comment by finddata** [comment]
While running show.sh the following erro ocurs:

cat: dir/p1/p1.config: No such file or directory
newdir [error opening dir]

0 directories, 0 files
cat: newdir/DEMO/DEMO.config: No such file or directory

**Comment by finddata** [comment]
Before this file we should runmakedirs.pl.If i run those file it prints cant locat module printer eror.

**Comment by hakonhagland** [comment]
You have to delete newdir structure first, alternatively run "run.sh"

2017-03-17 10:28 GMT+01:00 finddata <notifications@github.com>:

**Comment by finddata** [comment]
i had run that too.

**Comment by finddata** [comment]
What ever error you mentioned above i already corrected it.

**Comment by hakonhagland** [comment]
Ok thanks for spotting the problem in makedirs.pl, I removed the
Data::Printer module.
Try update the finddata Git reposistory to include my latest fix:

$ git pull origin master

then try run makedirs.pl again


2017-03-17 10:31 GMT+01:00 finddata <notifications@github.com>:

**Comment by finddata** [comment]
chdir: No such file or directory at makedirs.pl line 9.

**Comment by hakonhagland** [comment]
Ok thanks again for spotting another bug. I had to create the "dir"
directory first. I pushed a fix now. Can you try again please?

2017-03-17 10:39 GMT+01:00 finddata <notifications@github.com>:

**Comment by finddata** [comment]
Could you elaborate it in different sub routine which will be helpful for easy understanding.

One sub routien is for renaming contents and other is for renaming files .


my $top_dir = $output_dir;

rename_dirs( $top_dir, $name_map, $regex );
sub rename_dirs {
my ( $top_dir, $name_map, $regex ) = @_;
opendir (my $dh, $top_dir) or die "Can't open $top_dir: $!";
my $save_dir = getcwd();
chdir $top_dir;
while (my $name = readdir $dh) {
next if ($name eq '.') or ($name eq '..');
if ( ( -d $name ) && ( exists $name_map->{$name} ) ) {
my $new_name = $name_map->{$name};
rename_file_or_dir( $name, $new_name );
$name = $new_name;
}
elsif ( -f $name ) {
if (( my $base_name = $name) =~ s/.config$// ) {
if ( $name_map->{$base_name} ) {
my $new_name = $name_map->{$base_name} . '.config';
rename_file_or_dir( $name, $new_name );
change_file( $new_name, $name_map, $regex );
}
}
}

**Comment by finddata** [comment]
where you are calling this sub if_config_file_rename_and_modify_it subroutine as like rename_dirs(rename_dirs( $top_dir, $name_map, $regex );

**Comment by finddata** [comment]
My suggestion is create the directory manually as per i showed you in the example.Then run the same script which you had posted.Let me know if it works.

**Comment by hakonhagland** [comment]
I am not sure which example you refer to, and what script you have posted? Where have you posted it?

**Comment by finddata** [comment]
I mean the same script which we are already testing .

**Comment by finddata** [comment]
hi,

i struck with this following area .Could you please detail with every line with print statements.

The highlighted part prints nothing then how the contents will be renamed.
my $name_map = read_map( $mapfile );
my ($regex) = map {qr /\b(?:$_)\b/ } join '|', map {quotemeta} keys %$name_map;

my $top_dir = $output_dir;

rename_dirs( $top_dir, $name_map, $regex );
sub rename_dirs {
    my ( $top_dir, $name_map, $regex ) = @_;
    opendir (my $dh, $top_dir) or die "Can't open $top_dir: $!";
    my $save_dir = getcwd();
    chdir $top_dir;
    while (my $name = readdir $dh) {
        next if ($name eq '.') or ($name eq '..'); 
        if ( ( -d $name ) && ( exists $name_map->{$name} ) ) {
            my $new_name = $name_map->{$name};
            rename_file_or_dir( $name, $new_name );
            $name = $new_name;            
        }       
        elsif ( -f $name ) {
            if_config_file_rename_and_modify_it( $name, $name_map, $regex );
        }
        else
        {
         #print "  --> is not a directory", "\n";
         }

        if ( -d $name) { 
            
            rename_dirs( $name, $name_map, $regex );
            
            } 
    }
    chdir $save_dir;
}

sub if_config_file_rename_and_modify_it {
    my ( $name, $name_map, $regex ) = @_;
    if (( my $base_name = $name) =~ s/\.config$// ) {
        if ( $name_map->{$base_name} ) {
            **my $new_name = $name_map->{$base_name} . '.config';****(Already files are with .config and then why you concatenated again)**
           **print $new_name;(Here nothing is printed)** 
            rename_file_or_dir( $name, $new_name );
            change_file( $new_name, $name_map, $regex );
        }
    }
}

sub change_file {
    my ( $fn, $map, $regex ) = @_;
    **print "enter\n";**
    open ( my $fh, '<', $fn ) or die "Could not open file '$fn': $!";
    my $str = do { local $/; <$fh> };
    close $fh;
    my $num_replacements = $str =~ s/($regex)/$map->{$1}/ge;
    if ( $num_replacements ) {
        write_new_file( $fn, \$str );
    }
}

sub write_new_file {
    **print "enter1\n";**
    my ( $fn, $str ) = @_;
    open ( my $fh, '>', $fn ) or die "Could not open file '$fn': $!";
    print $fh $$str;
    close $fh;
}

sub rename_file_or_dir {

    my ( $name, $new_name ) = @_;
    File::Copy::move( $name, $new_name )
        or die "Could not rename '$name' as '$new_name': $!";
        #print $name;
}

sub read_map {
    my ( $fn ) = @_;

    my %name_map;

    open( my $fh, '<', $fn ) or die "Could not open file '$fn': $!";
    while( my $line = <$fh> ) {
        chomp $line;
        my @fields = split /:/, $line;
       # print @fields;
        if ( @fields == 3 ) {
            $name_map{$fields[2]} = $fields[1];
        }
    }
    close $fh;
    return \%name_map;
}

**Comment by hakonhagland** [comment]
Good morning!

What do you get when you run "run.sh"?

I get this output:

enter
enter1
enter



2017-03-20 8:55 GMT+01:00 finddata <notifications@github.com>:

**Comment by finddata** [comment]
Hi,

That is running fine only with this github folder(whichever you attached).I i took this p.pl and save it in different name and run it for other folders it fails.And the thing which i mentioned by bold in the above comment is not printing anything(i.e this line my $new_name = $name_map->{$base_name} . '.config';).And i couldnt get for what purpose you used it.

**Comment by hakonhagland** [comment]
Ok :) Can you please send me the other folder, for which it fails. Then I can check here if i can find the problem. By the way, `$new_name` is needed for the next two lines:

```
rename_file_or_dir( $name, $new_name );
change_file( $new_name, $name_map, $regex );
```

**Comment by finddata** [comment]
Is it possible to attach my folder here.

**Comment by hakonhagland** [comment]
I am not sure.. I can give you write access to the repository, then you could upload the folder in a new commit. Alternatively, use `tar cvf folder.tar folder` and `gzip folder.tar` and send me the folder
as an email attachment

**Comment by finddata** [comment]
Okay.

**Comment by finddata** [comment]
I had added my folder.Please look into it

**Comment by hakonhagland** [comment]
Ok thanks :) I pushed a new commit. Please check. It shows that none of the .config files are in
the match file

**Comment by finddata** [comment]
You how to check the .config files only under the following path .No need of considering other .config files.
./p.pl -prjroot "DCMS_DEMO/project_space" -outdir "DCMS_DEMO/new_dcms" -mapfile "DCMS_DEMO/mapfile.txt"

**Comment by hakonhagland** [comment]
Hello. To run the script against the `DCMS_DEMO/project_space` folder, you can type `run_DCMS.sh`

**Comment by finddata** [comment]
Hi,

Good morning.The think even if you execute the run_DCMS.sh.The contents inside the following destination ae not rewritten as like mapfile matching text(https://github.com/hakonhagland/finddata/blob/master/DCMS/new_dcms/DCMS_DEMO/project_status.config)

**Comment by finddata** [comment]
Now,

The following is your input directory config file:
https://github.com/hakonhagland/finddata/blob/master/DCMS/DCMS_DEMO/project_space/prj1/project_status.config

Destination directory:

https://github.com/hakonhagland/finddata/blob/master/DCMS/new_dcms/DCMS_DEMO/project_status.config

In the above Destination directory you are seeing the config file with its contents.Here the contents should be rewrriten as per mapfile.txt.

**Comment by finddata** [comment]
In Destination directory it is not happening .That is the issue which i tried to convey you.

**Comment by hakonhagland** [comment]
Good morning. If you look at the small example that we started with there is for example `p1` in the mapfile, and there is a folder `p1` and a config file `p1.config`. In the new example `DCMS/project_space` the is no `project_status` in the map file. That is the reason it will not change it.

**Comment by finddata** [comment]
The file contents renaming should be done recursively.You mentioned that there is no project_status.config under DCMS/project_space.You can check other directories too /DCMS/project_space/prj1/project_status.config

**Comment by finddata** [comment]
The think is we should consider all directories  recursively .under DCMS/DCMS_DEMO/project_space and rewrite its contents.No matter whether the file name is present or not.Whatever files which ends with .config extension under the directory DCMS/DCMS_DEMO/project_space.Those .config files should get matched with mapfile.txt and its contents to be rewritten.

**Comment by hakonhagland** [comment]
Ok, I understand. Let me have a look at `p.pl`, then we do not need to check if each config file is in the match file? ok?

**Comment by finddata** [comment]
No need to check the config file names in the match file.We need to consider only the contents inside the config files.If the file ends with .config extension we should look only the contents inside those files.File names are not required here.

**Comment by hakonhagland** [comment]
Ok :)  I changed `p.pl` according to your specification and pushed a new commit. Please check

**Comment by finddata** [comment]
Thanks a lot.Its working Great.You had done the great job.

**Comment by hakonhagland** [comment]
Great! Thanks for an interesting job. Please contact me any time if you like to discuss other programming (Perl) related problems.
Have a nice day!

**Comment by finddata** [comment]
Sure.Thank you once again.
