### ISSUE TITLE
Submit button fails to call the all subroutines using perl cgi?

### ISSUE THREAD

**Issue by finddata** [hakonhagland/finddata#4]
```
use CGI qw/:all/;
use CGI ':cgi-lib';
use Getopt::Long;
my $site;
GetOptions("site=s" => \$site)
    or die "Error in command line arguments\n";
    if($site eq ''){
      $site = 'Bangalore';
    }
defined $site
   or die "usage: $0 site_name\n";
my %site_map = (
    B  => [ qw(r_b_current) ],
    N    => [ qw(r_n_current) ],
    W => [ qw(r_w_current) ],
    L   => [ qw(r_l_current) ],
);
ShowContents()
sub ShowContents {
	my @arr = @{$site_map{$site}};
	print "***@arr**";
  	SBhpy($arr[0]);
	 print_overall_summary($arr[0]);  
}
print start_form(-method=>"GET",-action=>"rs.cgi");
print " <br> &nbsp<B>Site</B> &nbsp";
print popup_menu(

       -name    => 'popup1',
       -values  => [sort keys %site_map],
       #-default => 'value2'
         );
print "&nbsp &nbsp &nbsp &nbsp &nbsp  ";

print submit(-type=>'button',-value=>'submit',-onclick=>"ShowContents()");
#print submit(-type=>'button',-value=>'submit');
print end_form;

```
1.I had included only part of the script for your reference.
2.Here am unable load the subroutine when submit button is clicked.
3.Whenever if submit button B is clicked it show load the subroutine once.
4.Then if submit button L is clicked it should load the subroutine again.
5.Now the problem the script rs.cgi fails to load its script every time when submit is selected.
For your reference :+1: 
In browser i checked with inspect element.Here it shows that as follows:

input type="submit" name=".submit" value="submit" onclick="ShowContents()"==$0

Here $0 is not loading the script.How can i overcome this issue.

**Comment by hakonhagland** [comment]
Hi.. great that you solved your other issue. I have never used Perl and CGI, but I did a quick search and found this:

http://stackoverflow.com/questions/36697313/perl-cgi-onclick-call-perl-subroutine

It seems that you cannot call `ShowContents` directly. Is that correct??

**Comment by finddata** [comment]
Okay.But the same method i had used in my script.Hence it fails.
